name: Build Site

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        #uses: actions/checkout@master
        with:
          submodules: true
          fetch-depth: 0
      - name: Add save directory
        run: |
          git config --global --add safe.directory /github/workspace
      #- name: Build Site
      #  uses: chabad360/hugo-actions@master
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.117.0'
          # extended: true
      - name: Build
        run: hugo --minify

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public  
